name: Test program for A11
on: [push]
jobs:
  automated_test:
    name: Automated Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10 again
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Run find_lowest_number
      run: python find_lowest_number.py numbers.txt lowest_number.txt
